services:
  ch-tab-api:
    build: .
    image: ch-tab-api
    container_name: ch-tab-api
    depends_on:
      - ch-tab-api-cosmos-db
      - ch-tab-api-monogo-db
    environment:
      COSMOS_ENDPOINT: ${COSMOS_ENDPOINT}
      COSMOS_KEY: ${COSMOS_KEY}
  
  ch-tab-api-cosmos-db:
    image: mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator

  ch-tab-api-monogo-db:
    image: mongo:latest
    ports:
      - "27017:27017"